### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MedadRufus** [ImperialSpaceSociety/LoRaMac-node#30]
## Edits done over the reference version by STMicroelectronics

- [x] Switching LoRaMAC regional settings depending on where it is
- [x] Reduce tx power over US915/AU915
- [x] Prevent sending empty frame after boot
- [x] Use subband of 8 channels for US915/AU915
- [x] Seperate credentials for each region of the world.
- [x] Prevent sticky uplinks after receiving channel change requests. Actually prevent any uplinks to test channel change requests. wait till the next scheduled uplink.
- [x] Different datarate for each region
- [x] Polling specific date ranges for eeprom records
